--- 
global: 
  evaluation_interval: 120s
  external_labels: 
    monitor: Monitoring-project
  scrape_interval: 120s
rule_files: ~
scrape_configs: 
  - 
    job_name: prometheus
    scrape_interval: 120s
    static_configs: 
      - 
        targets: 
          - "localhost:9090"
          - "cadvisor:8080"
          - "node-exporter:9100"
          - "nginx-exporter:9113"
